In [2]:

import os
os.chdir("C:\\Users\\ancy\\Downloads\\Edureka\\Class 9")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
TrainData=pd.read_csv("Python_Module_Day_15.2_Credit_Risk_Train_data_XTRAIN.csv")
TestData=pd.read_csv("Python_Module_Day_15.4_Credit_Risk_Validate_data_XTEST.csv")

In [4]:
TrainData.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
TrainData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
Loan_ID              614 non-null object
Gender               601 non-null object
Married              611 non-null object
Dependents           599 non-null object
Education            614 non-null object
Self_Employed        582 non-null object
ApplicantIncome      614 non-null int64
CoapplicantIncome    614 non-null float64
LoanAmount           592 non-null float64
Loan_Amount_Term     600 non-null float64
Credit_History       564 non-null float64
Property_Area        614 non-null object
Loan_Status          614 non-null object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.4+ KB


In [6]:
TrainData

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
6    LP001013    Male     Yes          0  Not Graduate            No   
7    LP001014    Male     Yes         3+      Graduate            No   
8    LP001018    Male     Yes          2      Graduate            No   
9    LP001020    Male     Yes          1      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
12   LP001028    Male     Yes          2      Graduate            No   
13   LP001029    Male      No          0      Graduate            No   
14   LP001030    Male     Yes          2      Graduate            No   
15   LP001032    Male      No          0      Graduate            No   
16   LP001034    Male      No          1  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
18   LP001038    Male     Yes          0  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
20   LP001043    Male     Yes          0  Not Graduate            No   
21   LP001046    Male     Yes          1      Graduate            No   
22   LP001047    Male     Yes          0  Not Graduate            No   
23   LP001050     NaN     Yes          2  Not Graduate            No   
24   LP001052    Male     Yes          1      Graduate           NaN   
25   LP001066    Male     Yes          0      Graduate           Yes   
26   LP001068    Male     Yes          0      Graduate            No   
27   LP001073    Male     Yes          2  Not Graduate            No   
28   LP001086    Male      No          0  Not Graduate            No   
29   LP001087  Female      No          2      Graduate           NaN   
..        ...     ...     ...        ...           ...           ...   
584  LP002911    Male     Yes          1      Graduate            No   
585  LP002912    Male     Yes          1      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
587  LP002917  Female      No          0  Not Graduate            No   
588  LP002925     NaN      No          0      Graduate            No   
589  LP002926    Male     Yes          2      Graduate           Yes   
590  LP002928    Male     Yes          0      Graduate            No   
591  LP002931    Male     Yes          2      Graduate           Yes   
592  LP002933     NaN      No         3+      Graduate           Yes   
593  LP002936    Male     Yes          0      Graduate            No   
594  LP002938    Male     Yes          0      Graduate           Yes   
595  LP002940    Male      No          0  Not Graduate            No   
596  LP002941    Male     Yes          2  Not Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
598  LP002945    Male     Yes          0      Graduate           Yes   
599  LP002948    Male     Yes          2      Graduate            No   
600  LP002949  Female      No         3+      Graduate           NaN   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
602  LP002953    Male     Yes         3+      Graduate            No   
603  LP002958    Male      No          0      Graduate            No   
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not 

In [7]:
df=TrainData["Loan_ID"]
TrainData.drop(["Loan_ID"], axis=1, inplace= True)

TrainData["LoanAmount"].fillna(TrainData["LoanAmount"].median(),inplace=True)
TrainData["Loan_Amount_Term"].fillna(TrainData["Loan_Amount_Term"].median(), inplace=True)


In [8]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(strategy="most_frequent")
TrainData=imp.fit_transform(TrainData)

In [9]:
from sklearn.preprocessing import LabelEncoder
label_1=LabelEncoder()
TrainData[:,0]=label_1.fit_transform(TrainData[:,0])
label_2=LabelEncoder()
TrainData[:,1]=label_2.fit_transform(TrainData[:,1])
label_3=LabelEncoder()
TrainData[:,2]=label_3.fit_transform(TrainData[:,2])
label_4=LabelEncoder()
TrainData[:,3]=label_4.fit_transform(TrainData[:,3])
label_5=LabelEncoder()
TrainData[:,4]=label_5.fit_transform(TrainData[:,4])
label_6=LabelEncoder()
TrainData[:,10]=label_6.fit_transform(TrainData[:,10])
label_7=LabelEncoder()
TrainData[:,11]=label_7.fit_transform(TrainData[:,11])

In [10]:
pd.DataFrame(TrainData).head(7)

0  1  2  3  4     5     6    7    8  9  10 11
0  1  0  0  0  0  5849     0  128  360  1  2  1
1  1  1  1  0  0  4583  1508  128  360  1  0  0
2  1  1  0  0  1  3000     0   66  360  1  2  1
3  1  1  0  1  0  2583  2358  120  360  1  2  1
4  1  0  0  0  0  6000     0  141  360  1  2  1
5  1  1  2  0  1  5417  4196  267  360  1  2  1
6  1  1  0  1  0  2333  1516   95  360  1  2  1

In [11]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categorical_features=[2,10])
TrainData=ohe.fit_transform(TrainData).toarray()

C:\Users\ancy\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ancy\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [12]:
pd.DataFrame(TrainData).head(7)

0    1    2    3    4    5    6    7    8    9    10      11      12  \
0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  5849.0     0.0   
1  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  4583.0  1508.0   
2  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  3000.0     0.0   
3  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  2583.0  2358.0   
4  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  6000.0     0.0   
5  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  5417.0  4196.0   
6  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  2333.0  1516.0   

      13     14   15   16  
0  128.0  360.0  1.0  1.0  
1  128.0  360.0  1.0  0.0  
2   66.0  360.0  1.0  1.0  
3  120.0  360.0  1.0  1.0  
4  141.0  360.0  1.0  1.0  
5  267.0  360.0  1.0  1.0  
6   95.0  360.0  1.0  1.0

In [13]:
Train=pd.DataFrame(TrainData)

In [14]:
x_train=Train.iloc[:,0:16].values

In [15]:
y_train=Train.iloc[:,16].values

In [16]:
TestData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 13 columns):
Loan_ID              367 non-null object
Gender               356 non-null object
Married              367 non-null object
Dependents           357 non-null object
Education            367 non-null object
Self_Employed        344 non-null object
ApplicantIncome      367 non-null int64
CoapplicantIncome    367 non-null int64
LoanAmount           362 non-null float64
Loan_Amount_Term     361 non-null float64
Credit_History       338 non-null float64
Property_Area        367 non-null object
outcome              367 non-null object
dtypes: float64(3), int64(2), object(8)
memory usage: 37.4+ KB


In [17]:
TestData.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
outcome               0
dtype: int64

In [18]:
df1=TestData["Loan_ID"]
TestData.drop(["Loan_ID"], axis=1, inplace= True)

TestData["LoanAmount"].fillna(TestData["LoanAmount"].median(),inplace=True)
TestData["Loan_Amount_Term"].fillna(TestData["Loan_Amount_Term"].median(), inplace=True)


In [19]:
from sklearn.impute import SimpleImputer
imp1=SimpleImputer(strategy="most_frequent")
TestData=imp.fit_transform(TestData)

In [20]:
pd.DataFrame(TestData).head()

0    1  2             3   4     5     6    7    8  9      10 11
0  Male  Yes  0      Graduate  No  5720     0  110  360  1  Urban  Y
1  Male  Yes  1      Graduate  No  3076  1500  126  360  1  Urban  Y
2  Male  Yes  2      Graduate  No  5000  1800  208  360  1  Urban  Y
3  Male  Yes  2      Graduate  No  2340  2546  100  360  1  Urban  Y
4  Male   No  0  Not Graduate  No  3276     0   78  360  1  Urban  N

In [21]:
from sklearn.preprocessing import LabelEncoder
label_t1=LabelEncoder()
TestData[:,0]=label_t1.fit_transform(TestData[:,0])
label_t2=LabelEncoder()
TestData[:,1]=label_t2.fit_transform(TestData[:,1])
label_t3=LabelEncoder()
TestData[:,2]=label_t3.fit_transform(TestData[:,2])
label_t4=LabelEncoder()
TestData[:,3]=label_t4.fit_transform(TestData[:,3])
label_t5=LabelEncoder()
TestData[:,4]=label_t5.fit_transform(TestData[:,4])
label_t6=LabelEncoder()
TestData[:,10]=label_6.fit_transform(TestData[:,10])
label_t7=LabelEncoder()
TestData[:,11]=label_t7.fit_transform(TestData[:,11])

In [22]:
pd.DataFrame(TestData).head()

0  1  2  3  4     5     6    7    8  9  10 11
0  1  1  0  0  0  5720     0  110  360  1  2  1
1  1  1  1  0  0  3076  1500  126  360  1  2  1
2  1  1  2  0  0  5000  1800  208  360  1  2  1
3  1  1  2  0  0  2340  2546  100  360  1  2  1
4  1  0  0  1  0  3276     0   78  360  1  2  0

In [23]:
from sklearn.preprocessing import OneHotEncoder
ohe1=OneHotEncoder(categorical_features=[2,10])
TestData=ohe1.fit_transform(TestData).toarray()

C:\Users\ancy\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ancy\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [24]:
Test=pd.DataFrame(TestData)
x_test=Test.iloc[:,0:16].values
y_test=Test.iloc[:,16].values

Model Applying

In [25]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\ancy\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [26]:
y_pred_log=logmodel.predict(x_test)

In [27]:
y_pred_log


array([1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1.

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_pred_log,y_test)

array([[ 56,   3],
       [ 21, 287]], dtype=int64)

In [29]:
accuracy_score(y_pred_log,y_test)

0.9346049046321526

In [30]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2)
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [31]:
y_knn=knn.predict(x_test)

In [32]:
confusion_matrix(y_knn,y_test)

array([[ 19,  44],
       [ 58, 246]], dtype=int64)

In [33]:
accuracy_score(y_knn,y_test)

0.7220708446866485

In [35]:
# NB
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [36]:
y_gnb=gnb.predict(x_test)

In [37]:
confusion_matrix(y_gnb,y_test)

array([[ 58,   8],
       [ 19, 282]], dtype=int64)

In [38]:
accuracy_score(y_gnb,y_test)

0.9264305177111717

In [39]:
#svm
from sklearn.svm import SVC
sv=SVC(kernel="rbf")
sv.fit(x_train,y_train)

C:\Users\ancy\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [40]:
y_rbf=sv.predict(x_test)

In [41]:
confusion_matrix(y_rbf,y_test)

array([[  1,   0],
       [ 76, 290]], dtype=int64)

In [42]:
accuracy_score(y_rbf,y_test)

0.7929155313351499

In [43]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion="entropy")
dtc.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [44]:
y_dtc=dtc.predict(x_test)

In [45]:
confusion_matrix(y_dtc,y_test)

array([[ 58,  63],
       [ 19, 227]], dtype=int64)

In [46]:
accuracy_score(y_dtc,y_test)

0.776566757493188

In [47]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(criterion="entropy")
rfc.fit(x_train,y_train)

C:\Users\ancy\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [48]:
y_rfc=rfc.predict(x_test)

In [49]:
confusion_matrix(y_rfc,y_test)

array([[ 69,  25],
       [  8, 265]], dtype=int64)

In [50]:
accuracy_score(y_rfc,y_test)

0.9100817438692098

In [52]:
PredictData=pd.read_csv("Python_Module_Day_15.3_Credit_Risk_Test_data.csv")
PredictData.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [53]:
PredictData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
Loan_ID              367 non-null object
Gender               356 non-null object
Married              367 non-null object
Dependents           357 non-null object
Education            367 non-null object
Self_Employed        344 non-null object
ApplicantIncome      367 non-null int64
CoapplicantIncome    367 non-null int64
LoanAmount           362 non-null float64
Loan_Amount_Term     361 non-null float64
Credit_History       338 non-null float64
Property_Area        367 non-null object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB


In [54]:
PredictData.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [55]:
df2=PredictData["Loan_ID"]
PredictData.drop(["Loan_ID"], axis=1, inplace= True)

PredictData["LoanAmount"].fillna(PredictData["LoanAmount"].median(),inplace=True)
PredictData["Loan_Amount_Term"].fillna(PredictData["Loan_Amount_Term"].median(), inplace=True)

In [56]:
from sklearn.impute import SimpleImputer
imp2=SimpleImputer(strategy="most_frequent")
PredictData=imp2.fit_transform(PredictData)

In [57]:
pd.DataFrame(PredictData).head()

0    1  2             3   4     5     6    7    8  9      10
0  Male  Yes  0      Graduate  No  5720     0  110  360  1  Urban
1  Male  Yes  1      Graduate  No  3076  1500  126  360  1  Urban
2  Male  Yes  2      Graduate  No  5000  1800  208  360  1  Urban
3  Male  Yes  2      Graduate  No  2340  2546  100  360  1  Urban
4  Male   No  0  Not Graduate  No  3276     0   78  360  1  Urban

In [58]:
from sklearn.preprocessing import LabelEncoder
label_p1=LabelEncoder()
PredictData[:,0]=label_p1.fit_transform(PredictData[:,0])
label_p2=LabelEncoder()
PredictData[:,1]=label_p2.fit_transform(PredictData[:,1])
label_p3=LabelEncoder()
PredictData[:,2]=label_p3.fit_transform(PredictData[:,2])
label_p4=LabelEncoder()
PredictData[:,3]=label_p4.fit_transform(PredictData[:,3])
label_p5=LabelEncoder()
PredictData[:,4]=label_p5.fit_transform(PredictData[:,4])
label_p6=LabelEncoder()
PredictData[:,10]=label_p6.fit_transform(PredictData[:,10])


In [59]:
pd.DataFrame(PredictData).head()

0  1  2  3  4     5     6    7    8  9  10
0  1  1  0  0  0  5720     0  110  360  1  2
1  1  1  1  0  0  3076  1500  126  360  1  2
2  1  1  2  0  0  5000  1800  208  360  1  2
3  1  1  2  0  0  2340  2546  100  360  1  2
4  1  0  0  1  0  3276     0   78  360  1  2

In [60]:
from sklearn.preprocessing import OneHotEncoder
ohe1=OneHotEncoder(categorical_features=[2,10])
PredictData=ohe1.fit_transform(PredictData).toarray()

C:\Users\ancy\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ancy\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [61]:
pd.DataFrame(PredictData).head()

0    1    2    3    4    5    6    7    8    9    10      11      12  \
0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  5720.0     0.0   
1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  3076.0  1500.0   
2  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  5000.0  1800.0   
3  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  2340.0  2546.0   
4  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  3276.0     0.0   

      13     14   15  
0  110.0  360.0  1.0  
1  126.0  360.0  1.0  
2  208.0  360.0  1.0  
3  100.0  360.0  1.0  
4   78.0  360.0  1.0

In [63]:
y_new=logmodel.predict(PredictData)

In [64]:
y_new

array([1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1.

In [65]:
df_y=pd.DataFrame(y_new)

In [66]:
df_pred=pd.DataFrame(PredictData)

In [68]:
pd.concat([df_pred,df_y],axis=1)

0    1    2    3    4    5    6    7    8    9    10       11       12  \
0    1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   5720.0      0.0   
1    0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   3076.0   1500.0   
2    0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   5000.0   1800.0   
3    0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   2340.0   2546.0   
4    1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0   3276.0      0.0   
5    1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0   2165.0   3422.0   
6    0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0   2226.0      0.0   
7    0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0   3881.0      0.0   
8    0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  13633.0      0.0   
9    1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0   2400.0   2400.0   
10   1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0   3091.0      0.0   
11   0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0   2185.0   1516.0   
12   0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0   4166.0      0.0   
13   0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  12173.0      0.0   
14   1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   4666.0      0.0   
15   0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0   5667.0      0.0   
16   0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   4583.0   2916.0   
17   0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0   3786.0    333.0   
18   1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   9226.0   7916.0   
19   1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0   1300.0   3470.0   
20   0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   1888.0   1620.0   
21   0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   2083.0      0.0   
22   1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0   3909.0      0.0   
23   1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   3765.0      0.0   
24   1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   5400.0   4380.0   
25   1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0      0.0  24000.0   
26   0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   4363.0   1250.0   
27   1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   7500.0   3750.0   
28   1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0   3772.0    833.0   
29   1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0   2942.0   2382.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...      ...   
337  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   2292.0   1558.0   
338  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0   2360.0   3355.0   
339  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   4333.0   2333.0   
340  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0   2623.0   4831.0   
341  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0   3972.0   4275.0   
342  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0   3522.0      0.0   
343  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   4700.0      0.0   
344  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   6858.0      0.0   
345  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   8334.0      0.0   
346  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0   3391.0   1966.0   
347  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0   2868.0      0.0   
348  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   3418.0   1380.0   
349  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0   2500.0    296.0   
350  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0   8667.0      0.0   
351  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   2283.0  15000.0   
352  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0   5817.0    910.0   
353  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0   5119.0   3769.0   
354  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0  0.0   5316.0    187.0   
355  0